//
// Generated file, do not edit! Created by opp_msgc 4.4 from messages/LinkCreationAnswer.msg.
//

#ifndef _LINKCREATIONANSWER_M_H_
#define _LINKCREATIONANSWER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ProtocolMessage_m.h"
        #include "ProtocolMessageUtils.h"
// }}



/**
 * Class generated from <tt>messages/LinkCreationAnswer.msg</tt> by opp_msgc.
 * <pre>
 * message LinkCreationAnswer extends ProtocolMessage
 * {
 *     
 *     int answer @enum(answer_e);
 * }
 * </pre>
 */
class LinkCreationAnswer : public ::ProtocolMessage
{
  protected:
    int answer_var;

  private:
    void copy(const LinkCreationAnswer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LinkCreationAnswer&);

  public:
    LinkCreationAnswer(const char *name=NULL, int kind=0);
    LinkCreationAnswer(const LinkCreationAnswer& other);
    virtual ~LinkCreationAnswer();
    LinkCreationAnswer& operator=(const LinkCreationAnswer& other);
    virtual LinkCreationAnswer *dup() const {return new LinkCreationAnswer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getAnswer() const;
    virtual void setAnswer(int answer);
};

inline void doPacking(cCommBuffer *b, LinkCreationAnswer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LinkCreationAnswer& obj) {obj.parsimUnpack(b);}


#endif // _LINKCREATIONANSWER_M_H_
