//
// Generated file, do not edit! Created by opp_msgc 4.4 from messages/LinkCreatedAdvice.msg.
//

#ifndef _LINKCREATEDADVICE_M_H_
#define _LINKCREATEDADVICE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ProtocolMessage_m.h"
// }}



/**
 * Class generated from <tt>messages/LinkCreatedAdvice.msg</tt> by opp_msgc.
 * <pre>
 * class LinkCreatedAdvice extends ProtocolMessage
 * {
 *     
 *     int otherNode;
 * }
 * </pre>
 */
class LinkCreatedAdvice : public ::ProtocolMessage
{
  protected:
    int otherNode_var;

  private:
    void copy(const LinkCreatedAdvice& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LinkCreatedAdvice&);

  public:
    LinkCreatedAdvice(const char *name=NULL);
    LinkCreatedAdvice(const LinkCreatedAdvice& other);
    virtual ~LinkCreatedAdvice();
    LinkCreatedAdvice& operator=(const LinkCreatedAdvice& other);
    virtual LinkCreatedAdvice *dup() const {return new LinkCreatedAdvice(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getOtherNode() const;
    virtual void setOtherNode(int otherNode);
};

inline void doPacking(cCommBuffer *b, LinkCreatedAdvice& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LinkCreatedAdvice& obj) {obj.parsimUnpack(b);}


#endif // _LINKCREATEDADVICE_M_H_
