//
// Generated file, do not edit! Created by opp_msgc 4.4 from messages/ProtocolMessage.msg.
//

#ifndef _PROTOCOLMESSAGE_M_H_
#define _PROTOCOLMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ProtocolMessage.msg</tt> by opp_msgc.
 * <pre>
 * message ProtocolMessage
 * {
 *     
 *     int source;
 *     
 *     int destination;
 * }
 * </pre>
 */
class ProtocolMessage : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;

  private:
    void copy(const ProtocolMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ProtocolMessage&);

  public:
    ProtocolMessage(const char *name=NULL, int kind=0);
    ProtocolMessage(const ProtocolMessage& other);
    virtual ~ProtocolMessage();
    ProtocolMessage& operator=(const ProtocolMessage& other);
    virtual ProtocolMessage *dup() const {return new ProtocolMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doPacking(cCommBuffer *b, ProtocolMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ProtocolMessage& obj) {obj.parsimUnpack(b);}


#endif // _PROTOCOLMESSAGE_M_H_
